site_name: HardOPS Docs
site_url: http://hardops-manual.readthedocs.io/
pages:
    - Getting Started:
        - Start: index.md
        - Introduction: introduction.md
        - Installation: installation.md
        - Getting Started: getstarted.md
        - Resources: resources.md
        - FAQs and SFQs: faq.md
    - Usage Information:
        - Hotkeys: hotkeys.md
        - Understanding The Prefs: preferences.md
    - Sharpening / Bevelling:
        - Sharpening Basics: sharpening.md
        - SSharpen: ssharpen.md
        - CSharpen: csharpen.md
        - Step: step.md
        - ClearSSharps: clearssharps.md
    - Functions / Systems:
        - tThick: tthick.md
        - Insert: inserts.md
        - Mirror: mirror_symmetry.md
        - Sstatus: sstatus.md
    - Hard Ops Menus:
        - Menu System: menu_system.md
        - Operations Submenu (Object Mode): operations.md
        - Meshtools Submenu (Object Mode): meshtools.md
        - HOPS Helper: helper.md
        - HUD / Overlay: hud.md
        - Material Menu / Helper: tips_material_menu.md
    - Tips:
        - Booleans And Curvature: tips_boolean.md

    - Changelog: changelog.md

markdown_extensions:
    - admonition
    - footnotes
theme: readthedocs
extra_css:
    - css/extra.css
