site_name: HardOPS Docs
site_url: http://hardops-manual.readthedocs.io/
pages:
    - Getting Started:
        - Start: index.md
        - Introduction: introduction.md
        - Installation: installation.md
        - Getting Started: getstarted.md
        - Resources: resources.md
        - FAQs and SFQs: faq.md
        - Settings: settings.md
    - Usage Information:
        - Hotkeys: hotkeys.md
        - Understanding The Prefs: preferences.md
    - Sharpening / Bevelling / Cutters:
        - Sharpening Basics: sharpening.md
        - SSharpen: ssharpen.md
        - CSharpen: csharpen.md
        - Step: step.md
        - cSlash: cslash.md
        - ClearSSharps: clearssharps.md
    - Systems:
        - Booleans: boolean.md
        - hopsTool: hopsTool.md
        - hopsSort: sorting.md
        - Sstatus: sstatus.md
        - Mirror: mirror_symmetry.md
        - Insert: inserts.md
        - Circulars: circular.md
        - SketchOps: sketchops.md
    - Functions:
        - tThick: tthick.md
        - bWidth: bwidth.md
        - 2dbevel: 2dbevel.md
    - Hard Ops Menus / Options:
        - Menu System: menu_system.md
        - Operations Submenu (Object Mode): operations.md
        - Meshtools Submenu (Object Mode): meshtools.md
        - HOPS Helper: helper.md
        - HUD / Overlay: hud.md
        - Material Menu / Helper: tips_material_menu.md
        - Rendersets: rendersets.md
        - Viewport Submenu: viewport.md
    - Additional Tips:
        - Booleans And Curvature: tips_boolean.md
        - Boolean Tips: tips_boolean_exp.md
        - Understanding Subdivision: subdivision.md
        - decalMACHINE: decalmachine.md
    - Changelog: changelog.md
    - Reporting Issues: issues.md

markdown_extensions:
    - admonition
    - footnotes
theme: readthedocs
extra_css:
    - css/extra.css
