site_name: HardOPS Docs
site_url: http://hardops-manual.readthedocs.io/
pages:
    - Get Started:
        - Start: index.md
        - Introduction: introduction.md
        - Installation: installation.md
        - Getting Started: getstarted.md
        #- FAQ: docs\legacy\faq.md
    - Hard Ops Information:
        - Hotkeys: hotkeys.md
        - Understanding The Prefs: preferences.md
    - Ssharpening:
        - Understanding Sharpening: sharpening.md
        - SSharpen: ssharpen.md
        - CSharpen: csharpen.md
        #- Step: docs\Hops\operators\sharpeners\step.md
        - ClearSSharps: clearssharps.md
    - Hard Ops Cutters:
        #- CSplit: docs\Hops\operators\cutters\csplit.md
        #- Rebool: docs\Hops\operators\cutters\rebool.md
    - Hard Ops Menus:
        #- HOPS Menu System: docs\Hops\menus\menu.md
        #- HOPS Helper: docs\Hops\menus\helper.md
        #- HOPS HUD: docs\Hops\menus\hud.md
        #- Material Menu: docs\Hops\menus\material_menu.md
    #- Changelog: changelog.md

markdown_extensions:
    - admonition
    - footnotes
theme: readthedocs
extra_css:
    - css/extra.css
