site_name: hopsDocs
site_url: http://hardops-manual.readthedocs.io/
pages:
    - Getting Started:
        - Sales Page: hops_official.html
        - Start: index.md
        - Introduction: introduction.md
        - Installation: installation.md
        - Getting Started: getstarted.md
        - Boolean Tips: boolean_beginner_tips.md
        - Resources: resources.md
        - Contact / Help: contact_help.md
        - FAQs and SFQs: faq.md
        - Settings: settings.md
    - Usage Information:
        - Hotkeys: hotkeys.md
        - Workflows: workflows.md
        - Understanding The Prefs: preferences.md
    - Sharpening / Bevelling / Cutters:
        - Sharpening Basics: sharpening.md
        - Sharpen: sharpen.md
        - cSlash: cslash.md
    - Main Options:
        - Bevel: bwidth.md
        - Solidify: tthick.md
        - Array: array.md
    - Systems:
        - Modifiers: modifiers.md
        - Booleans: boolean.md
        - hopsTool: hopsTool.md
        - hopsSort: sorting.md
        - Sstatus: sstatus.md
        - Mirror: mirror_symmetry.md
        - Insert: inserts.md
        - Circulars: circular.md
        - SketchOps: sketchops.md
        - SculptOps: sculptops.md
    - Edit Mode:
        - Mark: edit_marksharp.md
        - Edit Mode Modifiers: edit_mods.md
        - Booleans: edit_booleans.md
        - Mirror: mirror_symmetry.md
        - Operations: edit_operations.md
    - Hard Ops Menus / Options:
        - Menu System: menu_system.md
        - Operations (Object Mode): operations.md
        - Meshtools (Object Mode): meshtools.md
        - HOPS Helper: helper.md
        - HUD / Overlay: hud.md
        - Material Menu / Helper: tips_material_menu.md
        - Rendersets: rendersets.md
        - Viewport Submenu: viewport.md
    - Tutorial Discussion:
        - discussion_cylinoid.md
    - Additional Tips:
        - Shading: shading.md
        - Boolean Tips: boolean_beginner_tips.md
        - Booleans And Curvature: tips_boolean.md
        - Boolean Case Studies: tips_boolean_exp.md
        - decalMACHINE: decalmachine.md
    - Classic Pages:
        - SSharpen: ssharpen.md
        - CSharpen: csharpen.md
        - Step: step.md
        - ClearSSharps: clearssharps.md
        - Understanding Subdivision: subdivision.md
    - Changelog: changelog.md
    - Reporting Issues: issues.md

markdown_extensions:
    - admonition
    - footnotes
theme: readthedocs
extra_css:
    - css/extra.css
